### ISSUE TITLE
Potential real world one-time key mismatch

### ISSUE THREAD

**Issue by gtklocker** [monero-rs/monero-rs#11]
We present a case where the one-time key generated by this library does not match what a Monero node verifies.

Full testcase can be found here: https://gist.github.com/gtklocker/e37c790471c02bb0249b0b430e455a61

Based on this transaction:
https://monero-stagenet.exan.tech/search?value=c0c95cf3bdc1340cd2844db709e904672eb134621d79799b82296db7a2ee691a

We deserialize the transaction:
```rust
    let tx = deserialize::<Transaction>(&tx_bytes).unwrap();
```

The txid is printed to ensure that parsing was correct:
```rust
    println!("txid={}", tx.hash());
    // => txid=0xc0c9…691a
```

We know both the private spend and view keys of the receiver at the output indexed 1, and we import them in the code.
```rust
    let secret_view_bytes = hex::decode("bcfdda53205318e1c14fa0ddca1a45df363bb427972981d0249d0f4652a7df07").unwrap();
    let secret_view = PrivateKey::from_slice(&secret_view_bytes).unwrap();
    let public_view = PublicKey::from_private_key(&secret_view);

    let secret_spend_bytes = hex::decode("e5f4301d32f3bdaef814a835a18aaaa24b13cc76cf01a832a7852faf9322e907").unwrap();
    let secret_spend = PrivateKey::from_slice(&secret_spend_bytes).unwrap();
    let public_spend = PublicKey::from_private_key(&secret_spend);
```

Another sanity check, checking that the address printed matches the one on our wallet, so the keys are correct.
```rust
    println!("address={}", Address::standard(Network::Testnet, public_spend, public_view));
```

Prints (disregard the formatting as testnet address):
```
address=5AnR6YFDqc66fZuNoR9EYBFJeweoqcn1hWSP8irRhYd38hxU5tD2b3Cdbee3yDySxs3A7ka8xZgxcDyFG8qbHfbk42Eupku
```

We extract `R` from the transaction:
```rust
    let public_r = tx.prefix.extra.tx_pubkey().unwrap();
```

where R is shown in the output as
```
tx pubkey=Some(5d1402db663eda8cef4f6782b66321e4a990f746aca249c973e098ba2c0837c1)
```

And compute and compare the one-time key for the output at index 1:
```rust
    println!("actual one-time key={:?}", tx.prefix.outputs[1].target);
    println!("computed one-time key={}", KeyGenerator::from_key(&ViewPair { view: secret_view, spend: public_spend }, public_r).one_time_key(1));
```

Which yields:
```
actual one-time key=ToKey { key: e3e77faca64b5997ac1f75763e87713d03d9e2896edec65843ffd2970ef1dde6 }
computed one-time key=8a4b0ef310c0afc51e8038e0852d613858fe639d58d7238ee95f5f0d3a4e463e
```

Entering the address and private viewing key in the explorer decodes the second input just fine.

I read the code responsible for generating the one-time keys and did not find anything obviously incorrect. I also noticed that the code is tested so the problem is probably in our use of the library. I would appreciate pointers with regards to that.

This issue was initially reported by @ladislavdubravsky.

**Comment by h4sh3d** [comment]
Hi, thanks for reporting this. I started investigating and for now what I saw is that

```rust
println!("computed one-time key={}", KeyGenerator::from_key(&ViewPair { ... }, public_r)
    .one_time_key(1));
```
Should be
```rust
println!("computed one-time key={}", KeyGenerator::from_key(&ViewPair { ... }, public_r)
    .one_time_key(2));
```

because we check the second output and not the first. As mentioned [here](https://www.getmonero.org/library/Zero-to-Monero-1-0-0.pdf#subsection.5.2.1) we can see that t start at 1.

But it is still not correct, but right now I don't know why. It still need some investigation.

Using `check_outputs` on transaction prefix does not return the output neither.

**Comment by h4sh3d** [comment]
Ok, long journey in the Monero code and the doc... but I found the problem.

As mentioned in a footnote in [Zero to Monero, page 35, footnote 2](https://www.getmonero.org/library/Zero-to-Monero-1-0-0.pdf) and in the code [here](https://github.com/monero-project/monero/blob/8f6f674753bae7494e1ee4569004947d47a4e983/src/crypto/crypto.cpp#L193) we can see that all `aR` and `rA` operation are in fact `8*aR` and `8*rA`. That's the first part of the problem.

The second part is output indexes, you were right, it starts from 0 and not 1. Fixing these two things makes everything work as intended. Here is an example with the method for detecting outputs given a range of addresses:

```rust
let tx = deserialize::<Transaction>(&tx_bytes).unwrap();

println!("txid={:?}", tx.hash());
println!("tx outputs={:#?}", tx.prefix.outputs);
println!("tx pubkey={:#?}", tx.prefix.tx_pubkey());
println!(
    "tx additional pubkey={:#?}",
    tx.prefix.tx_additional_pubkeys()
);

let secret_view_bytes =
    hex::decode("bcfdda53205318e1c14fa0ddca1a45df363bb427972981d0249d0f4652a7df07").unwrap();
let secret_view = PrivateKey::from_slice(&secret_view_bytes).unwrap();
let public_view = PublicKey::from_private_key(&secret_view);

let secret_spend_bytes =
    hex::decode("e5f4301d32f3bdaef814a835a18aaaa24b13cc76cf01a832a7852faf9322e907").unwrap();
let secret_spend = PrivateKey::from_slice(&secret_spend_bytes).unwrap();
let public_spend = PublicKey::from_private_key(&secret_spend);

println!(
    "address={}",
    Address::standard(Network::Stagenet, public_spend, public_view)
);

let _public_r = tx.prefix.tx_pubkey().unwrap();

let keypair = KeyPair {
    view: secret_view,
    spend: secret_spend,
};
let view_pair = ViewPair {
    view: secret_view,
    spend: public_spend,
};

let scan_res = tx.prefix.check_outputs(&view_pair, 0..10, 0..10).unwrap();
println!("checked outputs={:#?}", scan_res);

for out in scan_res {
    let rec = out.recover_key(&keypair);
    println!("    one-time priv key={}", &rec);
    println!(
        "    one-time computed={}",
        PublicKey::from_private_key(&rec)
    );
    println!("       output pub key={}", out.get_pubkeys().unwrap()[0]);
}
```

I'll release a new version, if it's good for you I let you close this issue.

**Comment by gtklocker** [comment]
Thanks a lot for this! This is confirmed as working correctly by @ladislavdubravsky, so I'm closing the issue.
