### ISSUE TITLE
support for Monero 0.18 

### ISSUE THREAD

**Issue by delta1** [monero-rs/monero-rs#115]
Hi there, I see the latest version is 0.17.2, just wondering what is required to support 0.18 for the upcoming hardfork? 

Would be happy to help out, just need some help with what needs to happen

**Comment by delta1** [comment]
Related: https://github.com/monero-ecosystem/monero-rpc-rs/issues/71 

Maybe it's just that I need for https://github.com/comit-network/xmr-btc-swap/issues/1081

**Comment by h4sh3d** [comment]
Crate version `0.17.2` is a coincidence and not related to Monero version `0.17.x`, thus the library is compatible with this Monero version. I have to check if some breaking changes has been made in the hard-fork that impacts the lib and require an update.

**Comment by delta1** [comment]
Thanks so much @h4sh3d
