### ISSUE TITLE
Subaddress Account Index Support

### ISSUE THREAD

**Issue by FistedByDionysus** [monero-rs/monero-rs#118]
Looking at the docs for monero-rs it appears subaddress creation doesn't support major and minor account indexes

https://monerodocs.org/public-address/subaddress/

https://docs.rs/monero/latest/monero/util/address/struct.Address.html#method.subaddress or associated helper method could take in indexes for computing a subaddress view key.

At the maintainers of this library is interested in supporting this behavior or is it preferred for the caller to compute their own view keys for subaddresses?

**Comment by Boog900** [comment]
subaddress generation using major and minor account indexes is done [here](https://docs.rs/monero/latest/monero/cryptonote/subaddress/fn.get_subaddress.html)
