### ISSUE TITLE
support database types 

### ISSUE THREAD

**Issue by Boog900** [monero-rs/monero-rs#128]
Would this library be interested in supporting types relating to Moneros databases? 

I have done a draft of this [here](https://github.com/Boog900/monero-rs/tree/database2/src/database_types)

**Comment by h4sh3d** [comment]
If we add them I think it would make sense to do it under a feature flag. What are your plans for those Monero databases types?

**Comment by Boog900** [comment]
I am currently making a [crate for interacting with a Monero database](https://github.com/Boog900/monero-db-rs) and having this library's consensus encoding/ decoding has helped a lot. However to interact with most sub dbs new types are needed.

For example Monero does not store the non prune-able and prune-able tx data together so to read from the non prune-able database a new type is needed: [TransactionPruned](https://github.com/Boog900/monero-rs/blob/ea0999d3d640378dc20e7a7bbac36a999343ea26/src/database_types/transaction.rs#L33)  

This TransactionPruned struct could also be used for other things for example when doing a /gettransactions request from a pruned node

**Comment by h4sh3d** [comment]
Feel free to open a PR that adds these new types and if you think a feature would be a good idea feel free to create one.
