### ISSUE TITLE
Can this library send xmr, is there an example?

### ISSUE THREAD

**Issue by vae520283995** [monero-rs/monero-rs#14]

**Comment by h4sh3d** [comment]
Hi, no the library only support block and transaction parsing, some key derivation and computation, and output detection (without amount).

I plan to add amount recovery soon, but sending coin implies integration with bulletproof and signature generation, decoy selection, etc... which are too big for this project at the moment.

**Comment by vae520283995** [comment]
> Hi, no the library only support block and transaction parsing, some key derivation and computation, and output detection (without amount).
> 
> I plan to add amount recovery soon, but sending coin implies integration with bulletproof and signature generation, decoy selection, etc... which are too big for this project at the moment.

Thank you. I see
