### ISSUE TITLE
Block serialize deserialize not working

### ISSUE THREAD

**Issue by SWvheerden** [monero-rs/monero-rs#16]
It looks like the block serialize or deserialize is not working, or I am using the code wrong. 
I created a unit test to show the functionality: #15

**Comment by SWvheerden** [comment]
I managed to get the unit test passing, it looks like the serilise was not adding the length of 0 vec

**Comment by h4sh3d** [comment]
Thanks for reporting this, and thanks for submitting a fix!

**Comment by h4sh3d** [comment]
I merged the fix and plan to release `0.8.0` this week-end

**Comment by StriderDM** [comment]
@h4sh3d 

Please see https://github.com/monero-rs/monero-rs/pull/17 .

We had mistakenly thought that this was the fix, it reverts the previous PR. The test has been altered to better illustrate the issue we have run into.
