### ISSUE TITLE
Fails to build with serde 1.0.168+

### ISSUE THREAD

**Issue by kayabaNerve** [monero-rs/monero-rs#162]
https://github.com/monero-rs/monero-rs/blob/main/src/util/amount.rs#L1069-L1088

cautious changed its API in https://github.com/serde-rs/serde/commit/399ef081ecc36d2f165ff1f6debdcbf6a1dc7efb.

**Comment by h4sh3d** [comment]
I tried to reproduced the bug after ae26279303bce6f2b4fa3515b392fe1ced9a58ec

with `serde` version `1.0.188`

```
[[package]]
name = "serde"
version = "1.0.188"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cf9e0fcba69a370eed61bcf2b728575f726b50b55cba78064753d708ddc7549e"
dependencies = [
 "serde_derive",
]
```

Everything compiles and run fine. Here is what a tried:

```rust
use serde::{Serialize, Deserialize};
use monero::Amount;

#[derive(Debug, Serialize, Deserialize)]
pub struct HasAmount {
    #[serde(
        default,
        serialize_with = "monero::util::amount::serde::as_pico::slice::serialize",
        deserialize_with = "monero::util::amount::serde::as_pico::vec::deserialize_amount"
    )]
    pub amounts: Vec<Amount>
}

fn main() {
    let s: HasAmount = serde_json::from_str(r#"
{ 
    "amounts": [123, 2244, 24312]
}
    "#).unwrap();
    println!("{:#?}", s);
    println!("{}", serde_json::to_string(&s).unwrap());
}
```

I would be very surprised if a patch version on serde's side breaks implementations. Can you re-validate the issue after updating `monero` and `monero-rpc`.

**Comment by kayabaNerve** [comment]
The issue was monero-rs used a private component from serde, which wasn't covered by any guarantees.

See https://github.com/serde-rs/serde/issues/2534 for a MRE and documentation.

**Comment by kayabaNerve** [comment]
vorot93 fixed this in https://github.com/monero-rs/monero-rs/commit/091957d36b37acaf2b53a9a34a0fcd7367cef7f4, and I forgot to pin the code snippet I linked to a specific commit. Closing.
