### ISSUE TITLE
Cold Signing 

### ISSUE THREAD

**Issue by oatsvine** [monero-rs/monero-rs#187]
I'm looking for a pure Rust crate to use as the offline wallet component of this workflow: https://monerodocs.org/cold-storage/offline-transaction-signing/ I'm sharing this as a reference, but I'm not expecting this library to do more than the cryptography required. 

I understand that this crate can a) create the offline wallet key material; b) deserialize the unsigned transaction; c) recover outputs from the read-only wallet. Based on my superficial understanding of the protocol, I'm unclear on what's involved in "sign_transfer" and "export_key_images". 

If this isn't on your roadmap, I would appreciate some guidance on how one might implement this. I may be able to contribute after doing my homework if need be.

**Comment by oatsvine** [comment]
I can across this: https://github.com/Cuprate/serai/tree/506ded205af576aee3927eb73c312395e673cc23/coins/monero/src/ringct I'm getting a clearer picture of what's involved.

**Comment by Boog900** [comment]
We don't want to support transactions signing see: #30

I would open an issue on [serai](https://github.com/serai-dex/serai), their Monero lib supports tx signing. I haven't looked into offline signing so I can't really help you sorry.
