### ISSUE TITLE
Question: Library Uses

### ISSUE THREAD

**Issue by NotGovernor** [monero-rs/monero-rs#190]
I'm looking for a rust library to talk to a wallet, create sub addresses, and verify payments received. Is this the best library for that purpose? If not do you have any recommendations?

Thanks!

**Comment by stringhandler** [comment]
I don't use this library for that, so I can't comment. 

There are two other monero rust crates if you don't find what you're looking for here.

https://github.com/Cuprate/cuprate
https://github.com/serai-dex/serai/tree/develop/coins/monero

**Comment by Boog900** [comment]
> talk to a wallet

if you mean monero-wallet-rpc then there is a crate for that: https://github.com/monero-rs/monero-rpc-rs

This  library can also be used to build a wallet without monero-wallet-rpc, see [AcceptXMR](https://github.com/busyboredom/acceptxmr). 

> create sub addresses, and verify payments received

yes this crate can do that

**Comment by NotGovernor** [comment]
Excellent -- so for a library to back a shopping cart it sounds like AcceptXMR is what I'm looking for. Thank you very much gentlemen!
