### ISSUE TITLE
Will this library support transfer in the future?

### ISSUE THREAD

**Issue by vae520283995** [monero-rs/monero-rs#30]
At present, there is no pure rust language library that supports transfer, I hope this can be the first.

**Comment by h4sh3d** [comment]
Hi, supporting transfer is currently out of scope for this library.

Transfers require more capability than just signing, constructing the transaction and choosing decoys is not really feasible inside the library itself, that's why it is out of scope.

**Comment by LeoNero** [comment]
@h4sh3d shall we close this issue?

**Comment by h4sh3d** [comment]
Closing as not planned, now that’s possible.
