### ISSUE TITLE
CLSAG encoding is incorrect

### ISSUE THREAD

**Issue by kayabaNerve** [monero-rs/monero-rs#79]
https://docs.rs/monero/0.16.0/src/monero/util/ringct.rs.html#365

Monero's CLSAG encoding does include the length prefix for this list.

A minimal C segment to trigger decoding is (assuming a monero-rs serialized CLSAG is in `s`):
```c
    rct::clsag clsag;
    std::stringstream ss;
    std::string str;
    str.assign((char*) s, (size_t) s_len);
    ss << str;
    binary_archive<false> ba(ss);
    ::serialization::serialize(ba, clsag);
    if (!ss.good()) {
      return false;
    }
```
This will fail without the length prefix.

**Comment by h4sh3d** [comment]
I’ll have a look why we did it like this, and extend the test suite to cover that. Thanks for pointing that issue.

Ideally I’d like to have a small test program that runs deserialize fn on every tx in the blockchain and log all errors, I think it’s time for that now ;)

**Comment by kayabaNerve** [comment]
That should also look at re-encoding as well to ensure serialization equivalence.

**Comment by kayabaNerve** [comment]
It looks like transactions don't include the length of s, yet any independent serialization will. This would explain why CLSAG encoding was only an issue now, as all previous usage has been for the TX as a whole.

I noted this when I was checking my [Python implementation](https://github.com/kayabaNerve/cryptonote-library/blob/master/cryptonote/crypto/monero_crypto.py#L191), and it matches monero-rs, yet the length of s is needed for the above C++. I'd be willing to close this accordingly, as there's not necessarily a clear solution available for both cases and this should already meet the expected usage for monero-rs.
